# Generated by Django 4.0.4 on 2023-02-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0009_quiztaker_connected_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
